### ISSUE TITLE
How to create many wallets at once like BIP32

### ISSUE THREAD

**Issue by kennethhutw** [binance-chain/javascript-sdk#120]
Hello , 

          There is a requirement to create many wallets at once for our clients. How to implement this feature? Is there any example ?

**Comment by notatestuser** [comment]
You could essentially just do this as many times as you want in a loop:

```js
// begin loop...
let mm
const addr = getAddressFromPrivateKey(
  getPrivateKeyFromMnemonic(mm = generateMnemonic()))
console.log('address', addr)
console.log('mnemonic', mm)
// end loop...
```

**Comment by kennethhutw** [comment]
By this way, I would need to keep as many Mnemonic phase as the wallet I create. It should like BIP32 way to generate wallet.

**Comment by notatestuser** [comment]
I am not sure that I completely understand the question, but one way or another **you will have to store either the seed entropy data or the derived private key**.

With this in mind, I would suggest storing the seed entropy (mnemonic phrase) so that you can derive multiple addresses for each phrase.

However, if you would just like to derive one default address for each mnemonic phrase, you could use the following method: [`crypto.getPrivateKeyFromMnemonic`](https://github.com/binance-chain/javascript-sdk/wiki/API-Documentation#module_crypto.getPrivateKeyFromMnemonic).

Here is an example:

```js
const mm = crypto.generateMnemonic()
const privateKey = crypto.getPrivateKeyFromMnemonic(mm, true)
// privateKey represents the derived private key hexstring, which you can store
```

**Comment by kennethhutw** [comment]
Hello @notatestuser I think you are talking about [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) However, I want [BIP32  ](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki)( Hierarchical Deterministic wallet ,HD Wallet ).  

https://www.npmjs.com/package/hdkey
```
var seed = 'fffcf9f6f3f0edeae7e4e1dedbd8d5d2cfccc9c6c3c0bdbab7b4b1aeaba8a5a29f9c999693908d8a8784817e7b7875726f6c696663605d5a5754514e4b484542'
var hdkey = HDKey.fromMasterSeed(Buffer.from(seed, 'hex'))
var childkey = hdkey.derive("m/0/2147483647'/1")
 
console.log(childkey.privateExtendedKey)
// -> "xprv9zFnWC6h2cLgpmSA46vutJzBcfJ8yaJGg8cX1e5StJh45BBciYTRXSd25UEPVuesF9yog62tGAQtHjXajPPdbRCHuWS6T8XA2ECKADdw4Ef"
console.log(childkey.publicExtendedKey)
// -> "xpub6DF8uhdarytz3FWdA8TvFSvvAh8dP3283MY7p2V4SeE2wyWmG5mg5EwVvmdMVCQcoNJxGoWaU9DCWh89LojfZ537wTfunKau47EL2dhHKon"
```

Is it the same as your answer? Thank you for your reply.
