### ISSUE TITLE
Ledger support

### ISSUE THREAD

**Issue by notatestuser** [binance-chain/javascript-sdk#40]
* Basic wallet management / transactions
* Multi-token balances and transfers
* Nice to have: multi-address (HD path) support

**Comment by joadr** [comment]
This requires the installation of extra operative system libraries such as libudev-dev, libusb-dev, usbutils. Deploying apps that use these libraries is becoming a bit complex because of this, and I bet most users won't be using these features. What about moving those functionalities to a separate package? I mean, enforcing users to install OS specific software for running an npm package is bad practice, more when it's just needed for one use case.

**Comment by joadr** [comment]
@notatestuser I'm actually having a really hard time deploying my app to elastic beanstalk because of this :(

**Comment by notatestuser** [comment]
Good point - We can look into making the ledger features optional. Just have to figure out what the best way to do that would be!

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by joadr** [comment]
Believe it or not, I still cannot deploy my Binance integration because of this. Nodejs Amazon Beanstalk image uses only Linux AMI, and as it doesn't have hardware interfaces, it doesn't come with the libraries, not even on the repos. Also, they don't support docker on the images, so I'm not able to create an image and install the binaries manually.
I'm hating this SDK so much now. Sorry, but I think that was the worst desition ever. It's even sadder to have the code ready, working and ready to be deployed. This stupid thing is stopping a whole exchange from integrating to the Binance Network.

**Comment by notatestuser** [comment]
Feel free to make your own SDK for your own deployment situation. Until then, suggestions are accepted. This is an open source project.

Let me see if I can put together a small fix for this today.

**Comment by notatestuser** [comment]
Please try `v2.14.0` without installing optional dependencies
